// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Session struct {
	ID              int64
	Label           string
	StartTime       int64
	EndTime         int64
	SessionDuration int64
}

type Task struct {
	ID          int64
	Title       string
	Description sql.NullString
	Priority    int64
	Status      string
	DueDate     sql.NullInt64
	CreatedAt   int64
	CompletedAt sql.NullInt64
}
