// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const addTask = `-- name: AddTask :exec
INSERT INTO tasks (title, description, priority, status, due_date, created_at, completed_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type AddTaskParams struct {
	Title       string
	Description sql.NullString
	Priority    int64
	Status      string
	DueDate     sql.NullInt64
	CreatedAt   int64
	CompletedAt sql.NullInt64
}

func (q *Queries) AddTask(ctx context.Context, arg AddTaskParams) error {
	_, err := q.db.ExecContext(ctx, addTask,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.DueDate,
		arg.CreatedAt,
		arg.CompletedAt,
	)
	return err
}

const getSessionsInTimeframe = `-- name: GetSessionsInTimeframe :many
SELECT id, label, start_time, end_time, session_duration
FROM sessions
WHERE start_time BETWEEN ? AND ?
ORDER BY start_time DESC
`

type GetSessionsInTimeframeParams struct {
	FromStartTime int64
	ToStartTime   int64
}

func (q *Queries) GetSessionsInTimeframe(ctx context.Context, arg GetSessionsInTimeframeParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getSessionsInTimeframe, arg.FromStartTime, arg.ToStartTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.StartTime,
			&i.EndTime,
			&i.SessionDuration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, title, description, priority, status, due_date, created_at, completed_at
FROM tasks
WHERE id = ?
`

func (q *Queries) GetTaskByID(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listAllTasks = `-- name: ListAllTasks :many
SELECT id, title, description, priority, status, due_date, created_at, completed_at
FROM tasks
ORDER BY priority DESC, created_at DESC
`

func (q *Queries) ListAllTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, label, start_time, end_time, session_duration
FROM sessions
ORDER BY start_time DESC
LIMIT ?
`

func (q *Queries) ListSessions(ctx context.Context, limit int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.StartTime,
			&i.EndTime,
			&i.SessionDuration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, description, priority, status, due_date, created_at, completed_at
FROM tasks
WHERE status IN (/*SLICE:statuses*/?)
ORDER BY priority DESC, created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context, statuses []string) ([]Task, error) {
	query := listTasks
	var queryParams []interface{}
	if len(statuses) > 0 {
		for _, v := range statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveSession = `-- name: SaveSession :exec
INSERT INTO sessions (label, start_time, end_time, session_duration)
VALUES (?, ?, ?, ?)
`

type SaveSessionParams struct {
	Label           string
	StartTime       int64
	EndTime         int64
	SessionDuration int64
}

func (q *Queries) SaveSession(ctx context.Context, arg SaveSessionParams) error {
	_, err := q.db.ExecContext(ctx, saveSession,
		arg.Label,
		arg.StartTime,
		arg.EndTime,
		arg.SessionDuration,
	)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks
SET title = ?, description = ?, priority = ?, status = ?, due_date = ?, completed_at = ?
WHERE id = ?
`

type UpdateTaskParams struct {
	Title       string
	Description sql.NullString
	Priority    int64
	Status      string
	DueDate     sql.NullInt64
	CompletedAt sql.NullInt64
	ID          int64
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.DueDate,
		arg.CompletedAt,
		arg.ID,
	)
	return err
}
